# Generated by Django 2.1.7 on 2019-03-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
